using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace G4Fit.Models.Enums
{
    public enum Errors
    {
        Success,
        RegisterDataIsRequired,
        InvalidPhoneNumber,
        NameFieldIsRequired,
        PhoneNumberFieldIsRequired,
        PasswordFieldIsRequired,
        PasswordFieldMustBeStringWithMinimumLengthOf6Chars,
        PasswordAndConfirmationPasswordDoNotMatch,
        SomethingIsWrong,
        PhoneNumberAlreadyExists,
        FailedToCreateTheAccount,
        TokenProblemOccured,
        LoginDataIsRequired,
        ProviderFieldIsRequired,
        UserNotFound,
        WrongPasswordProvided,
        UserNotVerified,
        VerificationCodeFieldIsRequired,
        WrongVerificationCode,
        UserIsVerified,
        InvalidOperatingSystem,
        InvalidToken,
        FailedToUploadImage,
        WrongFacebookAccessToken,
        ChangePasswordDataIsRequired,
        OldPasswordFieldIsRequired,
        NewPasswordFieldIsRequired,
        FailedToChangePassword,
        PageMustBeGreaterThanZero,
        ServiceNotFound,
        UserNotAuthorized,
        SizeNotFound,
        ColorNotFound,
        BasketItemNotFound,
        CannotDecrease,
        UserBasketIsEmpty,
        OrderNotFound,
        CategoryNotFound,
        CountryIdFieldIsRequired,
        CountryNotFound,
        ProfileDataIsRequired,
        UserLoginIsNotFromG4FitApplication,
        UserDoesNotHaveCountry,
        UserIdentityIsRequired,
        PromoNotFound,
        PromoExpired,
        PromoCodeCannotBeAppliedToCurrentUser,
        UserReachedItsLimitInUsingThePromoCode,
        OrderCostDidnotMeatMinimumPromoCodeRequiredCost,
        UserIsBlocked,
        InvalidStartDate,
    }
}